/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./RootStack.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./packages/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    screens: {
      xs: "320px",
      sm: "375px",
      md: "390px",
      lg: "414px",
      xl: "428px",
      "2xl": "430px",
      "3xl": "480px",
    },
    fontFamily: {
      sans: ["DMSans_400Regular", "system-ui", "sans-serif"],
      "sans-medium": ["DMSans_500Medium", "system-ui", "sans-serif"],
      "sans-semibold": ["DMSans_600SemiBold", "system-ui", "sans-serif"],
      "sans-bold": ["DMSans_700Bold", "system-ui", "sans-serif"],
    },
    fontSize: {
      xs: "12px",
      sm: "14px",
      base: "16px",
      lg: "18px",
      xl: "20px",
      "2xl": "24px",
      "3xl": "30px",
      "4xl": "36px",
      "5xl": "48px",
      "6xl": "56px",
    },
    extend: {
      colors: {
        ink: "#10201F",
        water: {
          DEFAULT: "#5EAAA6",
          deep: "#277C78",
          mist: "#E6F1EF",
        },
        mist: "#E6F1EF",
        muted: "#71807E",
        primary: {
          50: "#E6F1EF",
          100: "#D4E8E6",
          200: "#A8D4D0",
          300: "#7CBEBA",
          400: "#5EAAA6",
          500: "#5EAAA6",
          600: "#277C78",
          700: "#1F6360",
          800: "#174A48",
          900: "#10201F",
        },
        success: {
          50: "#ECF5F0",
          500: "#3D7A5A",
          700: "#2E5C44",
        },
        warning: {
          50: "#F8F1E4",
          500: "#B07A2E",
          700: "#8A5F24",
        },
        text: {
          primary: "#10201F",
          secondary: "#71807E",
          muted: "#71807E",
          disabled: "#A3B0AE",
          inverse: "#FFFFFF",
        },
        background: {
          primary: "#F7F8F6",
          secondary: "#FFFFFF",
          tertiary: "#E6F1EF",
          accent: "#E6F1EF",
        },
        border: {
          light: "#E8EEEC",
          default: "#D8E0DE",
          dark: "#A3B0AE",
        },
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
      },
      spacing: {
        11.3: "11.3rem",
        4.25: "4.25rem",
        43: "43px",
        280: "280px",
      },
    },
  },
  plugins: [],
};
